### ISSUE TITLE
Who can port the mod to 1.20.1?

### ISSUE THREAD

**Issue by Silver00177** [Ladysnake/Illuminations#174]
Who can port the mod to 1.20.1?

**Comment by UpcraftLP** [comment]
Why not use Effective, which has literally all features of Illuminations?

**Comment by Silver00177** [comment]
I'll answer your answer well

**Comment by Silver00177** [comment]
I'm not asking for similar features

**Comment by Silver00177** [comment]
I asked another question! You're not writing and answering what I've demanded or asked

**Comment by Silver00177** [comment]
And so I will ask the question who ports could to version 1 20 1

**Comment by Xiribidus** [comment]
Illuminations has already been ported to 1.20.1.
Bad news is it moved to quilt, although most fabric mods work on quilt as well so switching shouldn't be an issue.
Good news is it got a bunch of new features and effects, check it out [here](https://modrinth.com/mod/effective).
(It also got a slight rebranding due to all the changes)

**Comment by CammiePone** [comment]
> I'm not asking for similar features

1. she didnt say similar features, she said all the features. Illuminations was merged with Effective to become one mod
2. you don't need to send each and every sentence as a different comment. this isn't discord or texting, this is github
3. you don't have to be so rude to people spending their free time to try and help you. they arent getting paid to help you, they're doing it because they want to help

**Comment by Silver00177** [comment]
thank
