### ISSUE TITLE
Illuminations not showing on modded server

### ISSUE THREAD

**Issue by MrKashew** [Ladysnake/Illuminations#38]
illuminations show on singleplayer with the mods but not on the server with mods, tried having it installed on just client and and client + server

Version 1.0.4 on fabric

**Comment by doctor4t** [comment]
What do you mean it doesn't show? Illuminations is client only, meaning you can't install it on a server, as it won't do anything.
I personally tested this with multiple clients with the mod on a server and illuminations are correctly displayed on all of these clients. I'm gonna need more information because I really don't understand your issue here.

**Comment by MrKashew** [comment]
I have illuminations installed on my client and see them on single player worlds, but don't see them when I join a server. Have optifine and optifabric + shaders going, but assuming its not a problem as illuminations are showing on single player

**Comment by doctor4t** [comment]
Can you describe the conditions of the world on your server? Are you in the correct spawn biomes for fireflies to appear?

**Comment by MrKashew** [comment]
Modded biomes mostly (oh the biomes you'll go), but illuminations seems to appear correctly on SP, [here is a log](https://gist.github.com/MrKashew/a4426679ebb7b129abb0421acf76ff81), let me know if anything stands out; I'm guessing it's just some kind of incompatibility with my mods

**Comment by doctor4t** [comment]
I really don't see anything that stands out honestly. As a last ditch effort I'd say try and go into a swamp (a vanilla one) and see if you get any results, since swamps are the biomes with the highest firefly spawn rate.
Additionally, can you try and spawn a firefly particle on the server using `/particle illuminations:firefly` and tell me what you get, if you get anything?
