### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Gomez96** [Ladysnake/Illuminations#43]
I've an idea for fireflies in the Nether and End.

In the Nether they'd be scarlet, yellow (Same color of Blazes) and teal. 
Yellow in Crimson Forest and Basalt Deltas biome
Teal in Nether Wastes biome
Scarlet in Souls Sand Valley and Warped Forest biome

I didn't want to make fireflies colour blend in the biome of the same color, that's why I choose the other ones.

In the End they'd be purple and greenish-blue (Same color of Ender Pearl)
Greenish blue in islands close to End Cities and chorus plants.
Purple in empty islands deprived of chorus plants or far away from chorus plants.

**Comment by doctor4t** [comment]
I want to change things up a bit, and not just have firefly variations everywhere. I think more creativity would be better.

Maybe only teal fireflies in warped forests because they could support such life?
As for soulsand valleys, I think I may make spirits or souls that could fly around. Another possibility could also be that these souls would get freed if you break soul sand.

For the End I don't really know. I'll agree it's empty, but adding a third type of firefly would be really pushing it I feel, especially when endermen already emit so many particles.

**Comment by Moonflowey** [comment]
End could use purple-ish particles flying off of chorus flowers and gray-ish particles falling down from dead chorus flowers. Since chorus flowers are everywhere in the end, it'd cover most of the dimension.
Warped forests should also have the same particles (but teal-ish) randomly flying around, since according to mojang, "warped forests are affected by something that also affects the end", where only peaceful endermen spawn there.

**Comment by saltyseadoggo** [comment]
For the End dimension, perhaps some sort of white petals could drift around in the End highlands biome (the biome which generates chorus trees), as if the chorus flowers shed the white petals on their living texture when they turn purple and dead? Bonus points if a chorus flower dying generates a quick burst of them~ Also, I love the drifting souls idea for the soul sand valley!

**Comment by doctor4t** [comment]
> For the End dimension, perhaps some sort of white petals could drift around in the End highlands biome (the biome which generates chorus trees), as if the chorus flowers shed the white petals on their living texture when they turn purple and dead? Bonus points if a chorus flower dying generates a quick burst of them~

That is like, one of the best ideas I've ever heard, it sounds really cool, and I'm definitely gonna go with that!

**Comment by goldern** [comment]
Some suggestions:

**Nether**: Illuminated Fire Particles
**Nether Fortresses**: Glowing Black Smoke
**Ocean Monument**(Y low enough to be underwater and overmonument/sea floor): Prismarine (glows) Crystal shards
**Ocean**: Pacific Background(ish) Glowing Jellyfish, many colors/shapes
**Fire**: Upward flames (https://image.freepik.com/free-vector/flame-gold-fire-dark-transparent-background-with-red-sparks-flying-up-realistic_1284-32353.jpg)
**Redstone**: Glow in the dark

**Comment by doctor4t** [comment]
I wanted to add embers to campfire, as I thought it could look indeed really good and improve the ambiance when you are camping with one.
I don't know about the glowing black smoke and redstone ideas, but the prismarine shards near monuments are an excellent idea, and the jellyfish is already something I experimented with in the past, so we'll see.
