### ISSUE TITLE
Feature Request: Suport for Dynamic Lighting

### ISSUE THREAD

**Issue by Vaerian** [Ladysnake/Illuminations#49]
I feel like it would make this mod only that much more amazing to have support for [Dynamic Lights](https://github.com/LambdAurora/LambDynamicLights) when installed. Specifically for the fireflies, some of the other additions I could see being maybe not the best fit like the eyes in the dark.

**Comment by Pyrofab** [comment]
Having that many light sources would be quite laggy. Also fireflies really don't emit much light IRL.

**Comment by doctor4t** [comment]
That ^ I have said it many times and tried it in the past with Lumen and LightOrbs, this isn't such a good idea. It causes terrible performance, for a result that most of the time doesn't look remotely good.

However, since Illuminations is shader compatible, I suggest you try the mod with one. With some of them, the fireflies look really good with a nice glow, so that could maybe at least satisfy part of your request.
